/*
 * Employee List Api
 *
 * Hospital Employee Administration for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbelake@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

type EmployeeListEntry struct {

	// Unique id of the entry in this employee list
	Id string `json:"id"`

	// Name of employee in employee list
	Name string `json:"name,omitempty"`

	Role Role `json:"role,omitempty"`
}
